package com.shuiliandong.demo.simple.dao;

import com.shuiliandong.demo.simple.entity.DepartmentEntity;

public interface DepartmentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated
     */
    int insert(DepartmentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated
     */
    int insertSelective(DepartmentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated
     */
    DepartmentEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DepartmentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DepartmentEntity record);
}