package com.shuiliandong.demo.simple.dao;

import com.shuiliandong.demo.simple.entity.EmployeeCommunicationEntity;

public interface EmployeeCommunicationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_communication
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_communication
     *
     * @mbggenerated
     */
    int insert(EmployeeCommunicationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_communication
     *
     * @mbggenerated
     */
    int insertSelective(EmployeeCommunicationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_communication
     *
     * @mbggenerated
     */
    EmployeeCommunicationEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_communication
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmployeeCommunicationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_communication
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmployeeCommunicationEntity record);
}