package com.shuiliandong.demo.simple.dao;

import com.shuiliandong.demo.simple.entity.EmployeeInfoEntity;

public interface EmployeeInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_info
     *
     * @mbggenerated
     */
    int insert(EmployeeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_info
     *
     * @mbggenerated
     */
    int insertSelective(EmployeeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_info
     *
     * @mbggenerated
     */
    EmployeeInfoEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmployeeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmployeeInfoEntity record);
}