package com.shuiliandong.demo.simple.dao;

import com.shuiliandong.demo.simple.entity.PowerEntity;

public interface PowerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbggenerated
     */
    int insert(PowerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbggenerated
     */
    int insertSelective(PowerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbggenerated
     */
    PowerEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PowerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PowerEntity record);
}