package com.shuiliandong.demo.simple.dao;

import com.shuiliandong.demo.simple.entity.RolePowerRelationsEntity;

public interface RolePowerRelationsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_relations
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_relations
     *
     * @mbggenerated
     */
    int insert(RolePowerRelationsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_relations
     *
     * @mbggenerated
     */
    int insertSelective(RolePowerRelationsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_relations
     *
     * @mbggenerated
     */
    RolePowerRelationsEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_relations
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RolePowerRelationsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_relations
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RolePowerRelationsEntity record);
}