package com.shuiliandong.demo.simple.entity;

public class EmployeeCommunicationEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.employee_no
     *
     * @mbggenerated
     */
    private String employeeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.employee_id
     *
     * @mbggenerated
     */
    private Long employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.relationship_type
     *
     * @mbggenerated
     */
    private Integer relationshipType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.sort_no
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_communication.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.id
     *
     * @return the value of t_employee_communication.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.id
     *
     * @param id the value for t_employee_communication.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.employee_no
     *
     * @return the value of t_employee_communication.employee_no
     *
     * @mbggenerated
     */
    public String getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.employee_no
     *
     * @param employeeNo the value for t_employee_communication.employee_no
     *
     * @mbggenerated
     */
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo == null ? null : employeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.employee_id
     *
     * @return the value of t_employee_communication.employee_id
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.employee_id
     *
     * @param employeeId the value for t_employee_communication.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.type
     *
     * @return the value of t_employee_communication.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.type
     *
     * @param type the value for t_employee_communication.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.name
     *
     * @return the value of t_employee_communication.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.name
     *
     * @param name the value for t_employee_communication.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.desc
     *
     * @return the value of t_employee_communication.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.desc
     *
     * @param desc the value for t_employee_communication.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.relationship_type
     *
     * @return the value of t_employee_communication.relationship_type
     *
     * @mbggenerated
     */
    public Integer getRelationshipType() {
        return relationshipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.relationship_type
     *
     * @param relationshipType the value for t_employee_communication.relationship_type
     *
     * @mbggenerated
     */
    public void setRelationshipType(Integer relationshipType) {
        this.relationshipType = relationshipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.sort_no
     *
     * @return the value of t_employee_communication.sort_no
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.sort_no
     *
     * @param sortNo the value for t_employee_communication.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_communication.flag
     *
     * @return the value of t_employee_communication.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_communication.flag
     *
     * @param flag the value for t_employee_communication.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}