package com.shuiliandong.demo.simple.entity;

import java.util.Date;

public class EmployeeInfoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.employee_no
     *
     * @mbggenerated
     */
    private String employeeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.birth_year
     *
     * @mbggenerated
     */
    private String birthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.birth_month
     *
     * @mbggenerated
     */
    private String birthMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.birth_day
     *
     * @mbggenerated
     */
    private String birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.birth_date
     *
     * @mbggenerated
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.join_date
     *
     * @mbggenerated
     */
    private Date joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.leave_date
     *
     * @mbggenerated
     */
    private Date leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_info.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.id
     *
     * @return the value of t_employee_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.id
     *
     * @param id the value for t_employee_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.employee_no
     *
     * @return the value of t_employee_info.employee_no
     *
     * @mbggenerated
     */
    public String getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.employee_no
     *
     * @param employeeNo the value for t_employee_info.employee_no
     *
     * @mbggenerated
     */
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo == null ? null : employeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.name
     *
     * @return the value of t_employee_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.name
     *
     * @param name the value for t_employee_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.age
     *
     * @return the value of t_employee_info.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.age
     *
     * @param age the value for t_employee_info.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.id_card
     *
     * @return the value of t_employee_info.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.id_card
     *
     * @param idCard the value for t_employee_info.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.birth_year
     *
     * @return the value of t_employee_info.birth_year
     *
     * @mbggenerated
     */
    public String getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.birth_year
     *
     * @param birthYear the value for t_employee_info.birth_year
     *
     * @mbggenerated
     */
    public void setBirthYear(String birthYear) {
        this.birthYear = birthYear == null ? null : birthYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.birth_month
     *
     * @return the value of t_employee_info.birth_month
     *
     * @mbggenerated
     */
    public String getBirthMonth() {
        return birthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.birth_month
     *
     * @param birthMonth the value for t_employee_info.birth_month
     *
     * @mbggenerated
     */
    public void setBirthMonth(String birthMonth) {
        this.birthMonth = birthMonth == null ? null : birthMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.birth_day
     *
     * @return the value of t_employee_info.birth_day
     *
     * @mbggenerated
     */
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.birth_day
     *
     * @param birthDay the value for t_employee_info.birth_day
     *
     * @mbggenerated
     */
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay == null ? null : birthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.birth_date
     *
     * @return the value of t_employee_info.birth_date
     *
     * @mbggenerated
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.birth_date
     *
     * @param birthDate the value for t_employee_info.birth_date
     *
     * @mbggenerated
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.join_date
     *
     * @return the value of t_employee_info.join_date
     *
     * @mbggenerated
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.join_date
     *
     * @param joinDate the value for t_employee_info.join_date
     *
     * @mbggenerated
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.leave_date
     *
     * @return the value of t_employee_info.leave_date
     *
     * @mbggenerated
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.leave_date
     *
     * @param leaveDate the value for t_employee_info.leave_date
     *
     * @mbggenerated
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.status
     *
     * @return the value of t_employee_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.status
     *
     * @param status the value for t_employee_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_info.flag
     *
     * @return the value of t_employee_info.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_info.flag
     *
     * @param flag the value for t_employee_info.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}