package com.shuiliandong.demo.simple.entity;

public class RolePowerRelationsEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_power_relations.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_power_relations.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_power_relations.power_id
     *
     * @mbggenerated
     */
    private Long powerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_power_relations.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_power_relations.id
     *
     * @return the value of t_role_power_relations.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_power_relations.id
     *
     * @param id the value for t_role_power_relations.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_power_relations.role_id
     *
     * @return the value of t_role_power_relations.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_power_relations.role_id
     *
     * @param roleId the value for t_role_power_relations.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_power_relations.power_id
     *
     * @return the value of t_role_power_relations.power_id
     *
     * @mbggenerated
     */
    public Long getPowerId() {
        return powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_power_relations.power_id
     *
     * @param powerId the value for t_role_power_relations.power_id
     *
     * @mbggenerated
     */
    public void setPowerId(Long powerId) {
        this.powerId = powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_power_relations.flag
     *
     * @return the value of t_role_power_relations.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_power_relations.flag
     *
     * @param flag the value for t_role_power_relations.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}